version: "3.5"

networks:
  duplicacy_gui:

volumes:
  duplicacy_gui:

#secrets:
#  duplicacy_gui_admin_password:
#    name: ${STACK_NAME:-technocore}_duplicacy_gui_admin_password
#    external: true
#  duplicacy_gui_duplicacy_gui_db_password:
#    name: ${STACK_NAME:-technocore}_duplicacy_gui_duplicacy_gui_db_password
#    external: true
#  duplicacy_gui_db_duplicacy_gui_password:
#    name: ${STACK_NAME:-technocore}_duplicacy_gui_db_duplicacy_gui_password
#    external: true

services:
  ingress:
    networks:
      - duplicacy_gui

  duplicacy_gui:
    deploy:
      labels:
        - traefik.frontend.rule=$DUPLICACY_GUI_ROUTING_LABEL
        - traefik.frontend.priority=$DUPLICACY_GUI_ROUTING_LABEL_PRIORITY
        - traefik.port=3875
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_duplicacy_gui
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      #- MQTT_USER=${duplicacy_gui}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - HOSTNAME=${HOST_HOSTNAME}
    hostname: $HOST_HOSTNAME
    image: ${image_provider:-scififarms}/technocore-duplicacy-gui:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - duplicacy_gui
    #secrets:
    #  - source: duplicacy_gui_admin_password
    #    target: admin_password
    #  - source: duplicacy_gui_duplicacy_gui_db_password
    #    target: duplicacy_gui_db_password
    
    # IF YOU UPDATE THESE, ALSO UPDATE duplicacy-cli!
    volumes:
      - /:/data/root:ro

